"""
Toggle coverage analyzer for Project Ava.
Parses VCD files generated by Icarus Verilog simulations to compute
signal toggle coverage — which signals transitioned both 0→1 and 1→0.

Toggle coverage is a key metric for verification quality:
- Tells you which signals were actually exercised by your testbench
- Industry standard: verification engineers expect >90% toggle coverage
- Commercial tools (Cadence IMC, Synopsys URG) report this automatically

Usage:
    from src.coverage import analyze_coverage
    result = analyze_coverage("dump.vcd", toplevel="adder")
    print(f"Toggle: {result.toggle_pct:.1f}%")
"""

import re
from dataclasses import dataclass, field


@dataclass
class SignalCoverage:
    """Coverage data for a single signal."""
    name: str
    width: int
    bits_toggled: int         # Bits that saw both 0→1 and 1→0
    total_bits: int           # Total bit count
    toggle_pct: float         # bits_toggled / total_bits * 100


@dataclass
class CoverageResult:
    """Full coverage report for a design."""
    design_name: str
    total_signals: int
    total_bits: int
    toggled_bits: int
    toggle_pct: float
    signals: list = field(default_factory=list)  # List of SignalCoverage
    untoggled: list = field(default_factory=list)  # Signals with <100% toggle

    def to_dict(self) -> dict:
        return {
            "design_name": self.design_name,
            "total_signals": self.total_signals,
            "total_bits": self.total_bits,
            "toggled_bits": self.toggled_bits,
            "toggle_pct": round(self.toggle_pct, 1),
            "signals": [
                {
                    "name": s.name,
                    "width": s.width,
                    "toggled": s.bits_toggled,
                    "total": s.total_bits,
                    "pct": round(s.toggle_pct, 1),
                }
                for s in self.signals
            ],
            "untoggled_signals": [
                {"name": s.name, "pct": round(s.toggle_pct, 1)}
                for s in self.untoggled
            ],
        }


def analyze_coverage(vcd_path: str, toplevel: str = "",
                     exclude_clk_rst: bool = True) -> CoverageResult:
    """
    Analyze toggle coverage from a VCD file.

    Args:
        vcd_path: Path to VCD file
        toplevel: Top-level module name (for filtering signals)
        exclude_clk_rst: Exclude clk/rst/reset signals from coverage

    Returns:
        CoverageResult with toggle percentages
    """
    try:
        from vcdvcd import VCDVCD
    except ImportError:
        raise ImportError(
            "vcdvcd not installed. Run: pip install vcdvcd"
        )

    vcd = VCDVCD(vcd_path)

    signals_coverage = []
    total_bits = 0
    toggled_bits = 0

    for signal_name in sorted(vcd.references_to_ids.keys()):
        # Filter to toplevel module signals
        if toplevel and toplevel not in signal_name:
            continue

        # Skip clock and reset signals
        short_name = signal_name.split('.')[-1] if '.' in signal_name else signal_name
        if exclude_clk_rst:
            if short_name.lower() in ('clk', 'clock', 'rst', 'reset', 'rst_n', 'resetn'):
                continue

        signal = vcd[signal_name]
        tv = signal.tv  # list of (time, value) pairs

        if not tv:
            continue

        # Determine width from first value
        first_val = tv[0][1]
        width = len(first_val) if isinstance(first_val, str) else 1

        # Track 0→1 and 1→0 transitions for each bit
        saw_zero_to_one = [False] * width
        saw_one_to_zero = [False] * width

        for j in range(1, len(tv)):
            prev_val = str(tv[j-1][1])
            curr_val = str(tv[j][1])

            # Pad to same width
            prev_val = prev_val.zfill(width)
            curr_val = curr_val.zfill(width)

            for bit in range(width):
                pi = -(bit + 1)
                if pi >= -len(prev_val) and pi >= -len(curr_val):
                    p = prev_val[pi]
                    c = curr_val[pi]
                    if p == '0' and c == '1':
                        saw_zero_to_one[bit] = True
                    elif p == '1' and c == '0':
                        saw_one_to_zero[bit] = True

        # Count fully toggled bits (both 0→1 AND 1→0)
        sig_toggled = sum(
            1 for b in range(width)
            if saw_zero_to_one[b] and saw_one_to_zero[b]
        )

        total_bits += width
        toggled_bits += sig_toggled

        sig_cov = SignalCoverage(
            name=short_name,
            width=width,
            bits_toggled=sig_toggled,
            total_bits=width,
            toggle_pct=(sig_toggled / width * 100) if width > 0 else 0,
        )
        signals_coverage.append(sig_cov)

    toggle_pct = (toggled_bits / total_bits * 100) if total_bits > 0 else 0
    untoggled = [s for s in signals_coverage if s.toggle_pct < 100]

    return CoverageResult(
        design_name=toplevel or "unknown",
        total_signals=len(signals_coverage),
        total_bits=total_bits,
        toggled_bits=toggled_bits,
        toggle_pct=toggle_pct,
        signals=signals_coverage,
        untoggled=untoggled,
    )


def print_coverage(result: CoverageResult):
    """Print human-readable coverage report."""
    print(f"\n{'='*60}")
    print(f"  TOGGLE COVERAGE: {result.design_name}")
    print(f"{'='*60}")
    print(f"  Total signals:    {result.total_signals}")
    print(f"  Total bits:       {result.total_bits}")
    print(f"  Toggled bits:     {result.toggled_bits}")
    print(f"  TOGGLE COVERAGE:  {result.toggle_pct:.1f}%")
    print()

    print(f"  {'Signal':<30} {'Width':>6} {'Toggled':>8} {'Coverage':>9}")
    print(f"  {'-'*55}")
    for s in result.signals:
        marker = " " if s.toggle_pct == 100 else "*"
        print(f"  {s.name:<30} {s.width:>6} {s.bits_toggled:>8} {s.toggle_pct:>8.1f}%{marker}")

    if result.untoggled:
        print(f"\n  * = incomplete toggle coverage")
